[package]
name = "KnifeTools"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
clap = { version = "4.5.17", features = ["derive"]}
tokio = { version = "1", features = ["full"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "chrono"] }

[[bin]]
name = "LogSpliter"
path = "LogSpliter/main.rs"

